name: workflow1
on: push
jobs: 
  firstjob:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout Repo
       uses: actions/checkout@v4
     - name: welcome Message
       run: echo "Hello World"
     - name: List Files
       run : ls
     - name: Read File
       run: cat README.md